PASCAL   = ppc386
COPTDEBUG = -g -v0 -XS -Co -Ci -Cr -Ct -ddebugit
COPT = -v0  -g -XS -Co -Ci -Cr -Ct


linux: fidoconf2.pas erweiter.pas fparser.pas memman.pas utils.pas log.pas ini.pas match.pas fidoconfig.pas smapi.pas
	ppc386 $(COPT) -TLinux ffma.pas

linuxdebug: fidoconf2.pas erweiter.pas fparser.pas memman.pas utils.pas log.pas ini.pas match.pas fidoconfig.pas smapi.pas
	ppc386 $(COPTDEBUG) -TLinux ffma.pas
